name: Lint and Validate

on:
  push:
    branches: [ main, enhance-audit-suggestions ]
  pull_request:
    branches: [ main ]

jobs:
  lint-shell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run shellcheck on copy-prompts.sh
        run: |
          sudo apt-get update && sudo apt-get install -y shellcheck
          shellcheck copy-prompts.sh

  lint-markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint markdown files
        uses: DavidAnson/markdownlint-cli2-action@v15
        with:
          globs: '**/*.md'

  validate-prompts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check for required frontmatter in prompts/rules
        run: |
          missing=0
          for f in $(find . -type f \( -name '*.md' -o -name '*.mdc' \)); do
            if ! grep -q '^---' "$f"; then
              echo "Missing frontmatter: $f"
              missing=1
            fi
          done
          exit $missing
